version: "3.7"
services:
  redis:
    build:
      context: redis-srv
      dockerfile: Dockerfile
    networks:
      redis_schema_net:
        ipv4_address: 172.28.1.4
    expose:
      - "6379"
    ports:
      - "6379:6379"
  lua_debugger:
    tty: true
    build:
      context: lua
      dockerfile: Dockerfile
    networks:
      redis_schema_net:
        ipv4_address: 172.28.1.6
networks:
  redis_schema_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
